version: '3'
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
    
  api:
    build: .
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: mongodb://mongo_db:27017/test
    depends_on:
      - mongo_db

volumes:
  mongo_db:
      